User Suspend Views
dimagi/connect-id pull request #38
Opened 2024-07-08 12:26 UTC by pxwxnvermx

[Ticket](https://dimagi.atlassian.net/browse/CCCT-374)

2024-07-22 19:34 UTC, calellowitz reviewed
couple small things. The big one I made on the other PR but i think that connectid should call the connect view, not the mobile

2024-07-24 09:40 UTC, pxwxnvermx commented on users/oauth.py
> +    oidc_claim_scope = OAuth2Validator.oidc_claim_scope
This copies the claim scopes from the base class to our oauth2 validator class. Before only the `sub` was transferred when the userinfo endpoint was called. This allows us to get additional information on the claim.

2024-07-29 13:07 UTC, hemant10yadav approved these changes

2024-08-08 01:32 UTC, calellowitz requested changes
general approach looks good but i think there are a few bugs.

2024-08-08 01:32 UTC, calellowitz commented on users/views.py
> +    secret_key = data["secret_key"]
when does this secret key get set?

2024-08-08 01:32 UTC, calellowitz commented on users/views.py
> +        phone_device = PhoneDevice(phone_number=phone_number)
it looks like you are intending to fetch from the data base, but instead creating a new object. Also, if you did intend to query, this will also return devices if this number was ever used as a secondary number (for example if one worker put another's as their recovery number). I think you want to be fetching the user directly by phone number, like we do in the other recovery views, rather than the `PhoneDevice`

2024-08-08 01:32 UTC, calellowitz commented on users/views.py
> +        phone_device = PhoneDevice(phone_number=phone_number)
same comment about this as above

2024-08-08 01:32 UTC, calellowitz commented on users/models.py
>      phone_number = PhoneNumberField(unique=True)
sravan mentioned this on one of the specs, but we will need to update this constraint so that phone number is unique for active users, but not overall. i think you can do that by adding a unique constraint with `condition` https://docs.djangoproject.com/en/5.0/ref/models/constraints/#condition

2024-08-09 09:52 UTC, pxwxnvermx commented on users/models.py
>      phone_number = PhoneNumberField(unique=True)
Added. https://github.com/dimagi/connect-id/pull/38/commits/7a81ac5dcd6eb7471a97a3168321f932be073e45

2024-08-09 09:53 UTC, pxwxnvermx commented on users/views.py
> +        phone_device = PhoneDevice(phone_number=phone_number)
Fixed. Thanks. I did intend to query that. https://github.com/dimagi/connect-id/pull/38/commits/9bce35ba1fac9c8a08a079d8e1a6ad51514d8ecf

2024-08-09 09:54 UTC, pxwxnvermx commented on users/views.py
> +    secret_key = data["secret_key"]
This secret_key is the one from recovery status.

2024-08-12 22:15 UTC, calellowitz approved these changes

2024-08-12 22:15 UTC, merged