hy/stub out views
dimagi/connect-id pull request #42
Opened 2024-09-05 11:20 UTC by hemant10yadav

https://dimagi.atlassian.net/browse/CCCT-474

2024-10-16 05:22 UTC, sravfeyn commented on connectmessaging/apps.py
> +    name = "connectmessaging"
Why not use the existing `messaging` app?

2024-10-16 05:24 UTC, sravfeyn commented on connectmessaging/views.py
> +from messaging.serializers import Message as Msg
`nit` Recommend to use just Message instead of Msg

2024-10-16 05:27 UTC, sravfeyn commented on connectmessaging/views.py
> +                body="A new channel has been created for you. Please provide your consent to proceed.",
If this is a user-facing message, we should consider reframing this to on the lines of 'Please provide consent to send/receive messages', users don't need to be aware of the `channel` term

2024-10-16 05:28 UTC, sravfeyn commented on connectmessaging/views.py
> +            send_bulk_message(message)
Should this handle message failure?

2024-10-16 05:30 UTC, sravfeyn commented on connectmessaging/views.py
> +                            {"error": "Consent is required for this channel."},
It might make sense to send some sort of codenames for the caller to identify the error types.

2024-10-16 05:32 UTC, sravfeyn commented on connectmessaging/views.py
> +                        return Response(
Should this be a `JsonResponse`?

2024-10-16 05:37 UTC, sravfeyn commented on connectmessaging/views.py
> +                    if not Channel.objects.filter(
It might be worth refactoring the above `for` loop to avoid separate query for each message channel by making a single query to see if there are any missing channels.

2024-10-16 05:41 UTC, sravfeyn commented on connectmessaging/views.py
> +                            {"error": "Consent is required for this channel."},
This will result in partial success/failure. For e.g. if there are five messages to be sent and 3rd channel doesn't exist, first two messages will go and last three messages won't go even if the last two messages have channel. 
I am not sure what's required, whether we should fail on all messages or allow partial success. And if we allow partial success, whether that needs to be informed to caller.

2024-10-16 05:44 UTC, sravfeyn commented on connectmessaging/views.py
> +        return Response({"channels": channels_data, "messages": messages_data})
Shouldn't this be paginated?

2024-10-16 05:59 UTC, sravfeyn commented on connectmessaging/views.py
> +class UpdateConsentView(views.APIView):
How about permissions/auth? What permissions are needed to make this call?

2024-10-16 05:59 UTC, sravfeyn commented on connectmessaging/views.py
> +        return Response(status=status.HTTP_200_OK)
Should be a `JsonResponse`

2024-10-16 06:00 UTC, sravfeyn commented on connectmessaging/views.py
> +            return Response(status=status.HTTP_200_OK)
Should this be a `404`?

2024-10-16 06:12 UTC, sravfeyn commented on connectmessaging/views.py
> +        return Response(status=status.HTTP_200_OK)
Should probably send a status URL which the client can check for the status. @calellowitz ?

2024-10-16 08:34 UTC, hemant10yadav commented on connectmessaging/views.py
> +from messaging.serializers import Message as Msg
To avoid confusion with another Message model in the connectmessaging app, I made the following adjustments.

2024-10-16 08:46 UTC, hemant10yadav commented on connectmessaging/views.py
> +                            {"error": "Consent is required for this channel."},
You are right, but as I understand it, this endpoint will receive a single message from a mobile device, so it will handle just one message in that case. However, it could receive multiple messages when this endpoint is used by HQ. That's why I made it a list to create a common view, but I am not fully confident that only one message will be sent from a mobile. Perhaps @calellowitz can clarify this.

2024-10-16 08:50 UTC, hemant10yadav commented on connectmessaging/views.py
> +                    if not Channel.objects.filter(
[same](https://github.com/dimagi/connect-id/pull/42/files/aceba49c0a87618de4404b516d4a807a6fe42abe#r1802637970)

2024-10-16 09:01 UTC, hemant10yadav commented on connectmessaging/views.py
> +class UpdateConsentView(views.APIView):
If no `authentication_classes` are provided, the default authentication classes will be used.

Verified that APIView automatically uses DEFAULT_AUTHENTICATION_CLASSES
```
class APIView(View):
    authentication_classes = api_settings.DEFAULT_AUTHENTICATION_CLASSES
```

2024-10-16 09:32 UTC, hemant10yadav commented on connectmessaging/views.py
> +                body="A new channel has been created for you. Please provide your consent to proceed.",
Added the change.

2024-10-16 09:33 UTC, hemant10yadav commented on connectmessaging/views.py
> +                        return Response(
Thanks Changed to `JsonResponse`.

2024-10-17 01:01 UTC, calellowitz commented on connectmessaging/apps.py
> +    name = "connectmessaging"
As mentioned in our call, I agree with this

2024-10-17 01:03 UTC, calellowitz commented on connectmessaging/views.py
> +                            {"error": "Consent is required for this channel."},
I think you interpreted that backwards. Mobile will send many at a time (whenever it gets access to network), while HQ will send them individually since it can send them as soon as they are needed.

2024-10-17 01:05 UTC, calellowitz commented on connectmessaging/views.py
> +        return Response({"channels": channels_data, "messages": messages_data})
Since this is only supposed to send undelivered messages, and there aren't likely to be too many of those, I think it's fine to have it unpaginated for now. If we run into issues with a huge message backlog, we can reconsider.

2024-10-17 01:06 UTC, calellowitz commented on connectmessaging/views.py
> +        return Response(status=status.HTTP_200_OK)
Check which status?

2024-10-17 01:18 UTC, calellowitz requested changes
Left a few comments, both to agree with previous reviews and a few more suggestions. In addition, it would be good to add the `Server` model we discussed on the call today

2024-10-17 01:18 UTC, calellowitz commented on connectmessaging/views.py
> +        serializer = ChannelSerializer(data=request.data)
Is there an advantage to doing this over just using the model directly `Channel(...`?

2024-10-17 01:18 UTC, calellowitz commented on connectmessaging/views.py
> +            send_bulk_message(message)
If this fails, it should probably bubble back to hq, so it knows it needs to create it again.

2024-10-17 01:18 UTC, calellowitz commented on connectmessaging/views.py
> +        serializer = MessageSerializer(data=data, many=True)
Same question about using the serializer here vs the model directly

2024-10-17 01:18 UTC, calellowitz commented on connectmessaging/views.py
> +                message_to_send = Msg(
Does this class work for messages to HQ and to FCM? I would have imagined that an FCM specific class like that would have a different data model than what we send to hq

2024-10-17 01:18 UTC, calellowitz commented on connectmessaging/views.py
> +                if is_request_from_hq(request):
This isn't safe since we will have other sending services like OCS. The last time we chatted we discussed having different URLs from mobile and from sending services. I think that is probably the best idea since they will likely need different data and actions anyway.

2024-10-17 01:18 UTC, calellowitz commented on connectmessaging/task.py
> +@celery_app.task()
Let's leave this synchronous for now without celery for our testing. And we can add async before going live

2024-10-17 02:39 UTC, hemant10yadav commented on connectmessaging/views.py
> +                            {"error": "Consent is required for this channel."},
My bad I will update it accordingly.

2024-10-17 11:58 UTC, hemant10yadav commented on connectmessaging/views.py
> +        serializer = ChannelSerializer(data=request.data)
We need to extract keys from the data and catch any channel exceptions, so I thought using a serializer would result in much cleaner and more maintainable code than using the model directly. However, I can switch to using Channel(...) if you think that's the better approach.

2024-10-17 12:06 UTC, hemant10yadav commented on connectmessaging/views.py
> +                message_to_send = Msg(
This class only work for FCM notification. I think I accidentally placed it outside .

2024-10-23 02:42 UTC, calellowitz reviewed
Generally looks fine, left a couple comments about naming and one about the behavior of the message

2024-10-23 07:46 UTC, hemant10yadav commented on messaging/views.py
> +class SendMessageView(APIView):
Thanks! updated [3a6dfcb](https://github.com/dimagi/connect-id/pull/42/commits/3a6dfcbb47257807cf645a01b798b7885403a259)

2024-10-23 07:46 UTC, hemant10yadav commented on messaging/views.py
> +                data={"message_id": message.message_id, "content": message.content},
Added [3a6dfcb](https://github.com/dimagi/connect-id/pull/42/commits/3a6dfcbb47257807cf645a01b798b7885403a259)

2024-10-23 07:46 UTC, hemant10yadav commented on messaging/views.py
> +class SendFcmNotificationView(APIView):
Chaged [3a6dfcb](https://github.com/dimagi/connect-id/pull/42/commits/3a6dfcbb47257807cf645a01b798b7885403a259)

2024-10-23 08:47 UTC, sravfeyn commented on messaging/tests.py
> +            assert (
We don't need the assertion fail-part of these statements. If the tests fail, it will pretty much say the same along the lines of these statements.

2024-10-23 08:48 UTC, sravfeyn commented on messaging/tests.py
> +            assert (
We can skip the two asserts above since we have this here, right?

2024-10-23 09:41 UTC, hemant10yadav commented on messaging/tests.py
> +        assert len(json_data["messages"]) == 0, "Expected empty messages list"
Thanks! added the changes.

2024-10-23 23:54 UTC, calellowitz approved these changes
approving and merging for now so we can start testing, as issues come up we may need to make adjustments

2024-10-24 01:08 UTC, merged