endpoints to receive/forward hq invites
dimagi/connect-id pull request #51
Opened 2024-11-11 12:02 UTC by sravfeyn

[Spec](https://docs.google.com/document/d/1h9OlQDD7Jpygwyi-Zp6aU-_TQNkz4wOxw93ZOjkTwHY/edit?tab=t.0#heading=h.syj1ugk3stxe)
[Ticket](https://dimagi.atlassian.net/browse/CCCT-425)

2024-11-14 01:05 UTC, calellowitz reviewed
Couple small questions

2024-11-14 01:05 UTC, calellowitz commented on users/views.py
> +        callback_url = quote_plus(request.data["callback_url"])
where does `callback_url` come from and point to?

2024-11-14 01:05 UTC, calellowitz commented on users/views.py
> +    authentication_classes = [ClientProtectedResourceAuth]
Who makes this call? Is this not from mobile?

2024-11-20 09:49 UTC, sravfeyn commented on users/views.py
> +    authentication_classes = [ClientProtectedResourceAuth]
Yes, this is made by mobile.

# From spec
To accept invitation (when user confirms), call below endpoint

‘connectid.dimagi.com/users/confirm_hq_invite’

POST params
callback_url: callback_url (forwarded in deep link)
invite_code: invite_code (forwarded in deep link)
user_token: user’s active auth token

2024-11-20 09:52 UTC, sravfeyn commented on users/views.py
> +        callback_url = quote_plus(request.data["callback_url"])
This is all according to the modified spec.

This comes from HQ and it points to HQ's invite confirmation view. It's for actual invite confirmation, when mobile confirms it to ConnectID, ConnectID calls back HQ on callback_url with the user's token.

2024-11-20 09:53 UTC, sravfeyn commented on users/views.py
> +        callback_url = quote_plus(request.data["callback_url"])
This is the HQ change https://github.com/dimagi/commcare-hq/pull/34967/commits/407303f6c68034fd182f7325a2764eb3f608e74b

2024-11-20 09:55 UTC, sravfeyn commented
@calellowitz Please let me know if this is good to go.

2024-11-22 01:36 UTC, calellowitz commented on users/views.py
> +            response = requests.post(callback_url, data={"invite_code": invite_code, "token": user_token})
Are you planning to address this? Given your answer below about where this points, it should be doable to check it against an allowed list (only hq instances?)

2024-11-22 01:36 UTC, calellowitz commented on users/views.py
> +    authentication_classes = [ClientProtectedResourceAuth]
In that case, this auth is incorrect. It only works with oauth client credentials grants (what we use for connect or other servers). I think the default auth classes should be fine.

2024-11-22 01:42 UTC, calellowitz requested changes
Left a few questions on the new code in addition to the previous comments

2024-11-22 01:42 UTC, calellowitz commented on connectid/views.py
> +def deeplink(request, subpath):
Are we able to direct them directly to the play store? That is what we discussed on the call and seems to make the most sense if it is possible. Mobile seemed to believe that it would be.

2024-11-22 01:42 UTC, calellowitz commented on users/views.py
> +        details = f"{callback_url}/{username}/{invite_code}/{user_domain}/{user.username}"
I think we spoke about this a while ago, but why is this encoded as a path rather than using query params (which libraries on web and mobile could parse much more easily)?

2024-11-22 07:01 UTC, sravfeyn commented on connectid/views.py
> +def deeplink(request, subpath):
Right, I have updated it to redirect to the app.

<img width="1146" alt="Screenshot 2024-11-22 at 12 31 38 PM" src="https://github.com/user-attachments/assets/223ee5de-018d-45d3-9d9b-e98e9bd0229c">

2024-11-22 07:03 UTC, sravfeyn commented on users/views.py
> +        details = f"{callback_url}/{username}/{invite_code}/{user_domain}/{user.username}"
Yeah, I think there was some issue regarding formatting this using query params on mobile, this format was specified by mobile.

2024-11-22 07:07 UTC, sravfeyn commented on users/views.py
> +    authentication_classes = [ClientProtectedResourceAuth]
You are right! I will remove those classes.

2024-11-22 07:43 UTC, sravfeyn commented
@calellowitz Thanks for the review, I have followed up.

2024-11-24 22:32 UTC, calellowitz commented on connectid/views.py
> +    html_content = """
Why inline HTML instead of using a separate file

2024-11-24 22:32 UTC, calellowitz commented on connectid/settings.py
> +    "commcarehq.org",
how does this work? Specifically, if `commcarehq.org` is enough to catch `www.commcarehq.org` I would expect it to also catch staging, and if we need to be more specific, I would expect `www` to be required.

2024-11-24 22:32 UTC, calellowitz commented on users/views.py
> +        details = f"{callback_url}/{username}/{invite_code}/{user_domain}/{user.username}"
I spoke to @OrangeAndGreen and he seemed to believe query params would be better for them as well. Let's offline on slack about this with a mobile dev.

2024-11-27 12:46 UTC, sravfeyn commented on connectid/views.py
> +    html_content = """
I have moved it to its own dir.

2024-11-27 12:46 UTC, sravfeyn commented on connectid/settings.py
> +    "commcarehq.org",
Good point, I will add `www` to the list to be specific.

2024-11-27 12:51 UTC, sravfeyn commented on users/views.py
> +        details = f"{callback_url}/{username}/{invite_code}/{user_domain}/{user.username}"
Okay, I have updated this to use queryparams.

2024-11-27 12:53 UTC, sravfeyn commented
@calellowitz I have addressed your feedback, please have a look. I think the CodeQL failure is incorrect as it is not able to detect the trusted URL check that is added.

2024-11-28 15:15 UTC, sravfeyn commented
@calellowitz Bumping for review please.

2024-12-11 03:13 UTC, calellowitz approved these changes

2024-12-11 09:13 UTC, merged

2024-12-11 09:33 UTC, sravfeyn commented
Thanks @calellowitz please also review the corresponding HQ PR https://github.com/dimagi/commcare-hq/pull/34967/files#diff-dc2c79b556e950acc7dea90175fd5febba22bf9fa4faaba1b61c3b3d5acdc9e9